---
name: Build and Push alexandrecarlton/pokeapi-dump
on:
  - push
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Start PokeAPI
        run: make pokeapi-up

      - name: Build dump
        run: make dump

      - name: Stop PokeAPI
        if: always()
        run: make pokeapi-down

      # Push to Docker Hub, per:
      # - https://github.com/docker/build-push-action?tab=readme-ov-file#path-context
      # - https://github.com/docker/metadata-action?tab=readme-ov-file#basic

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: alexandrecarlton/pokeapi-dump
          tags: |
            type=sha
            type=raw,value=latest

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
